spring: 
    application: 
        name: spring-cloud-zuul 
server: 
     port: 9001 
eureka: 
    client:
        serviceUrl: 
            defaultZone: http://localhost01:8000/eureka/ 
zuul: 
    routes: 
        api-a: 
            path: /producer/**
            serviceId: spring-cloud-producer
 
 